"""Add profile fields to patient

Revision ID: 28db8fd75455
Revises: 
Create Date: 2025-11-04 09:28:16.848134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28db8fd75455'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender')
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
