"""Add about_me to Patient

Revision ID: 6ac028f7e533
Revises: ef2e2c9ba872
Create Date: 2026-03-11 15:22:39.844751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac028f7e533'
down_revision = 'ef2e2c9ba872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
