"""Add clinical_notes to treatment

Revision ID: ef2e2c9ba872
Revises: e6d71a7a4925
Create Date: 2026-03-08 19:01:45.748156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ef2e2c9ba872'
down_revision = 'e6d71a7a4925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_notes', sa.Text(), nullable=True))
        batch_op.alter_column('prescriptions_json',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.alter_column('prescriptions_json',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('clinical_notes')

    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
